### ISSUE TITLE
Make a Gradle target to launch Blue genes

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/bluegenes#210]
We need a target to launch bluegenes from our new gradle build system. Here's the target:

https://github.com/julie-sullivan/intermine/blob/gradle/intermine/webapp/build.gradle#L66-L73
```
task blueGenesStart(type: JavaExec) {
    classpath = configurations.providedRuntime
    main = "bluegenes.server"
    if (!hasProperty('config')) {
        throw new InvalidUserDataException("Please provide location of configuration file, e.g. -Pconfig=/path/to/config.edn")
    }
    environment("config", config)
}
```

1. Going to bluegenes throws this error:

```
[main] INFO org.eclipse.jetty.server.ServerConnector - Started ServerConnector@20276412{HTTP/1.1}{0.0.0.0:5005}
[main] INFO org.eclipse.jetty.server.Server - Started @6161ms
18-01-19 13:53:59 kermit INFO [bluegenes.server:32] - Bluegenes server started on port: 5005
[qtp2091367901-32] WARN org.eclipse.jetty.server.HttpChannel - /
java.io.FileNotFoundException: project.clj (No such file or directory)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:195)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at clojure.java.io$fn__10968.invokeStatic(io.clj:229)
        at clojure.java.io$fn__10968.invoke(io.clj:229)
        at clojure.java.io$fn__10881$G__10874__10888.invoke(io.clj:69)
        at clojure.java.io$fn__10980.invokeStatic(io.clj:258)
        at clojure.java.io$fn__10980.invoke(io.clj:254)
        at clojure.java.io$fn__10881$G__10874__10888.invoke(io.clj:69)
        at clojure.java.io$fn__10942.invokeStatic(io.clj:165)
        at clojure.java.io$fn__10942.invoke(io.clj:165)
        at clojure.java.io$fn__10894$G__10870__10901.invoke(io.clj:69)
        at clojure.java.io$reader.invokeStatic(io.clj:102)
        at clojure.java.io$reader.doInvoke(io.clj:86)
        at clojure.lang.RestFn.invoke(RestFn.java:410)
        at clojure.lang.AFn.applyToHelper(AFn.java:154)
        at clojure.lang.RestFn.applyTo(RestFn.java:132)
        at clojure.core$apply.invokeStatic(core.clj:659)
        at clojure.core$slurp.invokeStatic(core.clj:6862)
        at clojure.core$slurp.doInvoke(core.clj:6862)
        at clojure.lang.RestFn.invoke(RestFn.java:410)
        at bluegenes.index$version.invokeStatic(index.clj:8)
        at bluegenes.index$version.invoke(index.clj:8)
        at bluegenes.index$index.invokeStatic(index.clj:65)
        at bluegenes.index$index.invoke(index.clj:58)
        at bluegenes.routes$fn__19828.invokeStatic(routes.clj:14)
        at bluegenes.routes$fn__19828.invoke(routes.clj:11)
        at compojure.core$wrap_response$fn__1892.invoke(core.clj:158)
        at compojure.core$wrap_route_middleware$fn__1876.invoke(core.clj:128)
        at compojure.core$wrap_route_info$fn__1881.invoke(core.clj:137)
        at compojure.core$wrap_route_matches$fn__1885.invoke(core.clj:146)
        at compojure.core$routing$fn__1900.invoke(core.clj:185)
        at clojure.core$some.invokeStatic(core.clj:2693)
        at clojure.core$some.invoke(core.clj:2684)
        at compojure.core$routing.invokeStatic(core.clj:185)
        at compojure.core$routing.doInvoke(core.clj:182)
        at clojure.lang.RestFn.applyTo(RestFn.java:139)
        at clojure.core$apply.invokeStatic(core.clj:659)
        at clojure.core$apply.invoke(core.clj:652)
        at compojure.core$routes$fn__1904.invoke(core.clj:192)
        at clojure.lang.Var.invoke(Var.java:381)
        at ring.middleware.reload$wrap_reload$fn__21334.invoke(reload.clj:39)
        at ring.middleware.session$wrap_session$fn__20849.invoke(session.clj:108)
        at ring.middleware.format_params$wrap_format_params$fn__21972.invoke(format_params.clj:119)
        at ring.middleware.format_params$wrap_format_params$fn__21972.invoke(format_params.clj:119)
        at ring.middleware.format_params$wrap_format_params$fn__21972.invoke(format_params.clj:119)
        at ring.middleware.format_params$wrap_format_params$fn__21972.invoke(format_params.clj:119)
        at ring.middleware.format_response$wrap_format_response$fn__22141.invoke(format_response.clj:194)
        at ring.adapter.jetty$proxy_handler$fn__22344.invoke(jetty.clj:25)
        at ring.adapter.jetty.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a.handle(Unknown Source)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
        at org.eclipse.jetty.server.Server.handle(Server.java:499)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:258)
        at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
        at java.lang.Thread.run(Thread.java:748)

```

2. I don't like having to pass in the config file. It's counter to how InterMine does things. You can specify `-Drelease=beta` to use a different properties file but if you don't pass in anything, it defaults to <MINE_NAME>.properties. We could do something similar? Gradle can rename files etc. 

Tell @danielabutano

**Comment by julie-sullivan** [comment]
Change to use Java style properties instead of .edn files

Then I will update the Gradle to read in bluegenes properties from flymine.properties and create config.edn (whatever the new filename is).

**Comment by julie-sullivan** [comment]
https://github.com/intermine/bluegenes/tree/dev/config/dev
**Scenario 1**
User launches bluegenes for flymine. Has no extra properties. Gradle task will use the default values instead:

param | default value
------------ | -------------
server-port | 5000
logging-level | info
db-host | localhost
db-name | bluegenes-dev
db-username | username (from flymine dev)
db-password | password (from flymine dev)

The task will create config.edn and pass that to bluegenes.jar.

**Scenario 2**
User launches bluegenes for flymine. Has added extra properties to flymine.properties

```
# example additions to flymine.properties
bluegenes.server-port=5001
bluegenes.logging-level=info
bluegenes.db-host=prod1
bluegenes.db-name=bluegenes
bluegenes.db-username=josh
bluegenes.db-password=bananacakes
```
Gradle task extracts those parameters. (Uses defaults for params that are not present?) Creates a config.edn file. Passes that to bluegenes.jar.

**Comment by julie-sullivan** [comment]
None of the above changes the fact that a user can theoretically launch blue genes without having their own intermine.

**Comment by joshkh** [comment]
We're getting the stacktrace above because we read in `project.clj` to provide its version number via an end point (for checking compatibility). The `project.clj` file gets included in the uberjar but not in the skinnyjar.

https://github.com/intermine/bluegenes/blob/dev/src/clj/bluegenes/index.clj#L8

Let's take this out for now until we have a better understanding of our new deployment process.

**Comment by julie-sullivan** [comment]
@joshkh Nice detective work! Did you update the JAR? Should I try again?

**Comment by julie-sullivan** [comment]
```
[main] INFO org.eclipse.jetty.server.Server - Started @6011ms
18-01-22 12:52:08 kermit INFO [bluegenes.server:28] - Bluegenes server started on port: 5005
[qtp1240091493-40] WARN org.eclipse.jetty.server.HttpChannel - /js/compiled/app.js?v=
java.lang.NullPointerException: Response map is nil
        at ring.util.servlet$update_servlet_response.invokeStatic(servlet.clj:100)
        at ring.util.servlet$update_servlet_response.invoke(servlet.clj:91)
        at ring.util.servlet$update_servlet_response.invokeStatic(servlet.clj:95)
        at ring.util.servlet$update_servlet_response.invoke(servlet.clj:91)
        at ring.adapter.jetty$proxy_handler$fn__22346.invoke(jetty.clj:26)
        at ring.adapter.jetty.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a.handle(Unknown Source)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
        at org.eclipse.jetty.server.Server.handle(Server.java:499)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:258)
        at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
        at java.lang.Thread.run(Thread.java:748)
[qtp1240091493-33] WARN org.eclipse.jetty.server.HttpChannel - /js/compiled/app.js?v=
java.lang.NullPointerException: Response map is nil
        at ring.util.servlet$update_servlet_response.invokeStatic(servlet.clj:100)
        at ring.util.servlet$update_servlet_response.invoke(servlet.clj:91)
        at ring.util.servlet$update_servlet_response.invokeStatic(servlet.clj:95)
        at ring.util.servlet$update_servlet_response.invoke(servlet.clj:91)
        at ring.adapter.jetty$proxy_handler$fn__22346.invoke(jetty.clj:26)
        at ring.adapter.jetty.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a.handle(Unknown Source)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
        at org.eclipse.jetty.server.Server.handle(Server.java:499)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:258)
        at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
        at java.lang.Thread.run(Thread.java:748)

```

**Comment by julie-sullivan** [comment]
http://localhost:5005/js/compiled/app.js - is not there oh no
```
HTTP ERROR: 500

Problem accessing /js/compiled/app.js. Reason:

    Response map is nil
```

**Comment by julie-sullivan** [comment]
this target is working now!
